# Generated by glute's release workflow from packaging/glute.rb.in.
# Source of truth: git@studio.wevr.com:wevr/tech/glute.git, mirrored to
# github.com/MarcelInTO/glute. Hand edits here are overwritten by the next release.
class Glute < Formula
  desc "Terminal dashboard for GitLab CI/CD pipeline and job statistics"
  homepage "https://github.com/MarcelInTO/glute"
  version "0.0.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/MarcelInTO/glute/releases/download/v0.0.1/glute-0.0.1-darwin-arm64.tar.gz"
      sha256 "6a7be0c6fb403179adf05f182d3ab569dd3e0706bc4714974aa1ad5a169d3f1b"
    end
    on_intel do
      url "https://github.com/MarcelInTO/glute/releases/download/v0.0.1/glute-0.0.1-darwin-amd64.tar.gz"
      sha256 "49df79491fae9f1c70c5df351fc31a98cc4c20c9962592aecd51eb4e54994dde"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MarcelInTO/glute/releases/download/v0.0.1/glute-0.0.1-linux-arm64.tar.gz"
      sha256 "fa1a77291d725676d573a7837a91e673c5ef53848c3ba2aa92dfc50992e288f7"
    end
    on_intel do
      url "https://github.com/MarcelInTO/glute/releases/download/v0.0.1/glute-0.0.1-linux-amd64.tar.gz"
      sha256 "eea21b66764427ea601a6848414673f15fd4100ce7f99ee2086774ffea9db60b"
    end
  end

  def install
    bin.install "glute"
  end

  # The binary stamps the tag (with its leading v); the formula version is the
  # bare X.Y.Z Homebrew needs for comparison, hence the explicit "v" here.
  test do
    assert_match "glute v#{version}", shell_output("#{bin}/glute version")
  end
end
