# Generated by glute's release workflow from packaging/glute.rb.in.
# Source of truth: git@studio.wevr.com:wevr/tech/glute.git, mirrored to
# github.com/MarcelInTO/glute. Hand edits here are overwritten by the next release.
class Glute < Formula
  desc "Terminal dashboard for GitLab CI/CD pipeline and job statistics"
  homepage "https://github.com/MarcelInTO/glute"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/MarcelInTO/glute/releases/download/v0.1.0/glute-0.1.0-darwin-arm64.tar.gz"
      sha256 "a1eb7fa30e42997a16900f79f851dcf22b82cc0dde1db36d12ec7ad1442e76b1"
    end
    on_intel do
      url "https://github.com/MarcelInTO/glute/releases/download/v0.1.0/glute-0.1.0-darwin-amd64.tar.gz"
      sha256 "61a4d9f3e3b20f0fb9717c6b879e99ee549ceb81b44b097952aabca328e9e7f8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MarcelInTO/glute/releases/download/v0.1.0/glute-0.1.0-linux-arm64.tar.gz"
      sha256 "b893a88bc723e3b8d20169cdde64ad457553f462badf7aee7128ff4223305221"
    end
    on_intel do
      url "https://github.com/MarcelInTO/glute/releases/download/v0.1.0/glute-0.1.0-linux-amd64.tar.gz"
      sha256 "0b66651eaf87c9bb728567f472c7a41d68a1319d7a3db52bc8b23eaae5d1ca8e"
    end
  end

  def install
    bin.install "glute"
  end

  # The binary stamps the tag (with its leading v); the formula version is the
  # bare X.Y.Z Homebrew needs for comparison, hence the explicit "v" here.
  test do
    assert_match "glute v#{version}", shell_output("#{bin}/glute version")
  end
end
