# Generated by glute's release workflow from packaging/glute.rb.in.
# Source of truth: git@studio.wevr.com:wevr/tech/glute.git, mirrored to
# github.com/MarcelInTO/glute. Hand edits here are overwritten by the next release.
class Glute < Formula
  desc "Terminal dashboard for GitLab CI/CD pipeline and job statistics"
  homepage "https://github.com/MarcelInTO/glute"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/MarcelInTO/glute/releases/download/v0.2.0/glute-0.2.0-darwin-arm64.tar.gz"
      sha256 "10e1d9cacdb325b0e467772c38f5ba9459215b4e0ee6ac17a965624b1cd4bc68"
    end
    on_intel do
      url "https://github.com/MarcelInTO/glute/releases/download/v0.2.0/glute-0.2.0-darwin-amd64.tar.gz"
      sha256 "d2e002b7c08ba38ad7075bb6a1638535db0f9054b7886f37cfc15fea91474fe6"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/MarcelInTO/glute/releases/download/v0.2.0/glute-0.2.0-linux-arm64.tar.gz"
      sha256 "84e303faf62cc890516251b14a43ed8e339a147dfe805adf2752f0d15f823657"
    end
    on_intel do
      url "https://github.com/MarcelInTO/glute/releases/download/v0.2.0/glute-0.2.0-linux-amd64.tar.gz"
      sha256 "442e87b691bd22d7720a9e7676fa7c7430624e45997858a1eac68ad3029ada17"
    end
  end

  def install
    bin.install "glute"
  end

  # The binary stamps the tag (with its leading v); the formula version is the
  # bare X.Y.Z Homebrew needs for comparison, hence the explicit "v" here.
  test do
    assert_match "glute v#{version}", shell_output("#{bin}/glute version")
  end
end
